import localFont from "next/font/local";
import BurgerMenu from "./components/layout-components/BurgerMenu";
import Footer from "./components/layout-components/Footer";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "FooFest 2025",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <header>
          <BurgerMenu />
        </header>
        <main className="mx-mobile lg:mx-desktop">{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
